### PR TITLE
Fix authentication flow

### LINKED ISSUE #7: Not working with Contao 4.9.14
Modul is not working.
I created a notification, the module and put it on the website but if i put a username in the field and send nothing happens. No Errorlog. 

Also the translations are not visible. 
Only "token_login" for the Module and "member_token_login" for the Notification are visible.

### PR DESCRIPTION
**Pull request by richardhj**
Closes #7.

### CODE REVIEW

File: src/Module/TokenLogin.php [hunk 1]
```diff
@@ -166,7 +159,7 @@ protected function getResponse(Template $template, ModuleModel $model, Request $
         $template->action   = $request->getRequestUri();
         $template->slabel   = $this->translate('MSC.login');
         $template->value    = StringUtil::specialchars($this->authenticationUtils->getLastUsername());
-        $template->formId   = 'tl_login_' . $model->id;
+        $template->formId   = 't_login_' . $model->id;
```
Comment (richardhj) [inline src/Module/TokenLogin.php:162]: This is one of the main culprits I guess. We can change the form submit as we like.

```suggestion
        $template->formId   = 'tl_token_login_' . $model->id;
```

Comment (richardhj) [reply src/Module/TokenLogin.php:162]: > I only chose `t_login` to be consistent with your route🙂

Oh 🤔 that's nice

**Comment by richardhj** [comment]
LGTM. Backward compatibility with the redirect is no issue because links are only valid for 2 hours
